@extends($activeTemplate.'layouts.frontend')
@section('content')

<section class="about-section pt-50 pb-50" style="background-color: #f7f9f9;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-9 col-lg-10">
                <div class="about-card shadow-sm bg-white" style="border-radius: 12px; overflow: hidden; border: 1px solid #eee;">
                    
                    {{-- Premium Top Banner --}}
                    <div class="about-banner" style="background: linear-gradient(135deg, #db1e36, #a81528); padding: 45px 30px; text-align: center;">
                        <h2 class="text-white m-0" style="font-weight: 700; letter-spacing: 1px; font-size: 32px;">{{ __($pageTitle) }}</h2>
                        <p class="text-white-50 mt-2 mb-0" style="font-size: 16px;">Quality, Elegance, and Innovation</p>
                    </div>

                    {{-- Dynamic Content Wrapper --}}
                    <div class="about-dynamic-content p-4 p-md-5">
                        @php
                            echo @$content->data_values->details;
                        @endphp
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

@push('style')
<style>
    /* Styling the dynamic content block */
    .about-dynamic-content {
        color: #555;
        font-size: 16px;
        line-height: 1.8;
    }
    
    /* Make paragraphs spacing elegant */
    .about-dynamic-content p {
        margin-bottom: 24px;
        font-family: inherit;
    }
    
    /* Style Headings dynamically generated by the editor */
    .about-dynamic-content h1, 
    .about-dynamic-content h2, 
    .about-dynamic-content h3, 
    .about-dynamic-content h4 {
        color: #222;
        font-weight: 700;
        margin-top: 40px;
        margin-bottom: 20px;
        position: relative;
        padding-bottom: 12px;
    }
    
    /* Add an elegant red separator under headings */
    .about-dynamic-content h1::after,
    .about-dynamic-content h2::after,
    .about-dynamic-content h3::after {
        content: '';
        position: absolute;
        left: 0;
        bottom: 0;
        width: 60px;
        height: 3px;
        background: #db1e36;
        border-radius: 3px;
    }

    /* Target unordered lists (like Mission/Vision/Values usually are) */
    .about-dynamic-content ul {
        list-style: none;
        padding-left: 0;
        margin-bottom: 35px;
        margin-top: 20px;
    }
    
    .about-dynamic-content ul li {
        position: relative;
        margin-bottom: 15px;
        background: #fafafa;
        padding: 16px 20px 16px 45px;
        border-radius: 8px;
        border-left: 4px solid #db1e36;
        transition: all 0.3s ease;
        color: #333;
        font-weight: 500;
    }
    
    .about-dynamic-content ul li:hover {
        background: #fff;
        box-shadow: 0 5px 20px rgba(0,0,0,0.06);
        transform: translateY(-2px);
    }

    /* Add custom checkmark icon before list items */
    .about-dynamic-content ul li::before {
        content: '✔';
        position: absolute;
        left: 17px;
        top: 16px;
        color: #db1e36;
        font-size: 15px;
    }

    .about-dynamic-content strong, 
    .about-dynamic-content b {
        color: #111;
        font-weight: 600;
    }
</style>
@endpush

@endsection
